# Generated by Django 4.2.15 on 2024-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 3 characters', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_confirmation',
            field=models.CharField(help_text='To confirm, please enter your password again', max_length=50, verbose_name='Password confirmation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required field. No more than 150 characters. Only letters, numbers and symbols @/./+/-/_.', max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
