# Generated by Django 4.2.15 on 2024-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Your password must contain at least 3 characters.', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_confirmation',
            field=models.CharField(help_text='To confirm, please enter your password again.', max_length=50, verbose_name='Password confirmation'),
        ),
    ]
