# Generated by Django 4.2.15 on 2024-09-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password_alter_user_password_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_confirmation',
            new_name='password2',
        ),
    ]
